### ISSUE TITLE
Another bug for data 

### ISSUE THREAD

**Issue by miaojiang1987** [liruilong940607/glcic.pytorch#2]
Hi Ruilong Li,

I found another bug after modifying epochs for G and D.

Here is the report. 
Traceback (most recent call last):
  File "train.py", line 592, in <module>
    main()
  File "train.py", line 531, in main
    train(dataLoader, model_G, model_D, epoch)
  File "train.py", line 450, in train
    losses_G.update(loss_G.data[0], input3ch.size(0))
AttributeError: 'AverageMeter' object has no attribute 'data'

Does the data here mean val?

Best,
Miao

**Comment by liruilong940607** [comment]
@miaojiang1987 Sorry for the delay and thank you for pointing this bug.

I've fixed it and update the repo by modifying Line 449. in `train.py`.

**Comment by muni2773** [comment]
@miaojiang1987 Hi Miao, Can you please point me towards the dataset you used for train, validation and mask images. Appreciate your help. Thanks.

**Comment by miaojiang1987** [comment]
> @miaojiang1987 Hi Miao, Can you please point me towards the dataset you used for train, validation and mask images. Appreciate your help. Thanks.

@muni2773 , Hi, sorry that those dataset is private and belongs to an institution, I can not share. In addition to that, I also have trained places dataset.

**Comment by muni2773** [comment]
@miaojiang1987 Thanks Miao - I downloaded the Places dataset and used the small images Test as Train and Val as Val. I did 6 epochs with pkls in the snapshot directory but when I run is_train=false it is looking for a mask dataset. Do you know where the mask dataset is for Places?
